import { ReactComponent as Cuaca } from "./cuaca.svg";
import { ReactComponent as Visi } from "./visi.svg";
import { ReactComponent as Misi } from "./misi.svg";
import { ReactComponent as Experienced } from "./experienced.svg";
import { ReactComponent as Personalized } from "./personalized.svg";
import { ReactComponent as Customized } from "./customized.svg";
import { ReactComponent as Trusted } from "./trusted.svg";
import { ReactComponent as Cars } from "./cars.svg";
import { ReactComponent as PerBusiness } from "./perusahaan-feature.svg";
import { ReactComponent as ContactUs } from "./contactus.svg";
import { ReactComponent as Original } from "./original.svg";
import { ReactComponent as Quality } from "./quality.svg";
import { ReactComponent as Shield } from "./shield.svg";
import { ReactComponent as Guarantee } from "./guarantee.svg";
import { ReactComponent as Vision } from "./vision.svg";
import { ReactComponent as About } from "./about.svg";
import { ReactComponent as Group } from "./group.svg";

export const CuacaSvg = Cuaca;
export const VisiSvg = Visi;
export const MisiSvg = Misi;
export const ExperiencedSvg = Experienced;
export const PersonalizedSvg = Personalized;
export const CustomizedSvg = Customized;
export const TrustedSvg = Trusted;
export const CarsSvg = Cars;
export const PerBusinessSvg = PerBusiness;
export const ContactUsSvg = ContactUs;
export const OriginalSvg = Original;
export const QualitySvg = Quality;
export const ShieldSvg = Shield;
export const GuaranteeSvg = Guarantee;
export const VisionSvg = Vision;
export const AboutSvg = About;
export const GroupSvg = Group;
