name: Security Scan

on:
  schedule:
    - cron: '45 6 * * *' # daily scheduled scan at 13:45 WIB (06:45 UTC)
  pull_request:
    branches:
      - main

jobs:
  test_deep_scan:
    runs-on: ubuntu-latest
    name: Run a deep scan.
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Actual test
        uses: pentesttoolscom/pentesttools-github-action@master
        id: ptt
        with:
          target: https://karoseri.my.id/
          format: text
          fail: none
          type: deep
          key: ${{ secrets.SECRET_CI }}

      - name: Check the output
        run: echo "The report ${{ steps.ptt.outputs.result }}"
